package configuracao;

public class MontaEmail {

	public String montarEmailIndisponibilidade() {

		StringBuilder myvar = new StringBuilder();
		myvar.append(
				"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">")
				.append("<html xmlns:v=\"urn:schemas-microsoft-com:vml\">").append("").append("<head>")
				.append("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />")
				.append("    <meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0; maximum-scale=1.0;\" />")
				.append("    <meta name=\"viewport\" content=\"width=600,initial-scale = 2.3,user-scalable=no\">")
				.append("    <!--[if !mso]><!-- -->")
				.append("    <link href='https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700' rel=\"stylesheet\">")
				.append("    <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel=\"stylesheet\">")
				.append("    <!-- <![endif]-->").append("").append("    <title>Material Design for Bootstrap</title>")
				.append("").append("    <style type=\"text/css\">").append("        body {")
				.append("            width: 100%;").append("            background-color: #ffffff;")
				.append("            margin: 0;").append("            padding: 0;")
				.append("            -webkit-font-smoothing: antialiased;")
				.append("            mso-margin-top-alt: 0px;").append("            mso-margin-bottom-alt: 0px;")
				.append("            mso-padding-alt: 0px 0px 0px 0px;").append("        }").append("        ")
				.append("        p,").append("        h1,").append("        h2,").append("        h3,")
				.append("        h4 {").append("            margin-top: 0;").append("            margin-bottom: 0;")
				.append("            padding-top: 0;").append("            padding-bottom: 0;").append("        }")
				.append("        ").append("        span.preheader {").append("            display: none;")
				.append("            font-size: 1px;").append("        }").append("        ").append("        html {")
				.append("            width: 100%;").append("        }").append("        ").append("        table {")
				.append("            font-size: 14px;").append("            border: 0;").append("        }")
				.append("        /* ----------- responsivity ----------- */").append("        ")
				.append("        @media only screen and (max-width: 640px) {")
				.append("            /*------ top header ------ */").append("            .main-header {")
				.append("                font-size: 20px !important;").append("            }")
				.append("            .main-section-header {").append("                font-size: 28px !important;")
				.append("            }").append("            .show {")
				.append("                display: block !important;").append("            }")
				.append("            .hide {").append("                display: none !important;")
				.append("            }").append("            .align-center {")
				.append("                text-align: center !important;").append("            }")
				.append("            .no-bg {").append("                background: none !important;")
				.append("            }").append("            /*----- main image -------*/")
				.append("            .main-image img {").append("                width: 440px !important;")
				.append("                height: auto !important;").append("            }")
				.append("            /* ====== divider ====== */").append("            .divider img {")
				.append("                width: 440px !important;").append("            }")
				.append("            /*-------- container --------*/").append("            .container590 {")
				.append("                width: 440px !important;").append("            }")
				.append("            .container580 {").append("                width: 400px !important;")
				.append("            }").append("            .main-button {")
				.append("                width: 220px !important;").append("            }")
				.append("            /*-------- secions ----------*/").append("            .section-img img {")
				.append("                width: 320px !important;").append("                height: auto !important;")
				.append("            }").append("            .team-img img {")
				.append("                width: 100% !important;").append("                height: auto !important;")
				.append("            }").append("        }").append("        ")
				.append("        @media only screen and (max-width: 479px) {")
				.append("            /*------ top header ------ */").append("            .main-header {")
				.append("                font-size: 18px !important;").append("            }")
				.append("            .main-section-header {").append("                font-size: 26px !important;")
				.append("            }").append("            /* ====== divider ====== */")
				.append("            .divider img {").append("                width: 280px !important;")
				.append("            }").append("            /*-------- container --------*/")
				.append("            .container590 {").append("                width: 280px !important;")
				.append("            }").append("            .container590 {")
				.append("                width: 280px !important;").append("            }")
				.append("            .container580 {").append("                width: 260px !important;")
				.append("            }").append("            /*-------- secions ----------*/")
				.append("            .section-img img {").append("                width: 280px !important;")
				.append("                height: auto !important;").append("            }").append("        }")
				.append("    </style>").append("    <!-- [if gte mso 9]><style type=”text/css”>")
				.append("        body {").append("        font-family: arial, sans-serif!important;")
				.append("        }").append("        </style>").append("    <![endif]-->").append("</head>").append("")
				.append("")
				.append("<body class=\"respond\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">")
				.append("    <!-- pre-header -->").append("    <table style=\"display:none!important;\">")
				.append("        <tr>").append("            <td>")
				.append("                <div style=\"overflow:hidden;display:none;font-size:1px;color:#ffffff;line-height:1px;font-family:Arial;maxheight:0px;max-width:0px;opacity:0;\">")
				.append("                    Teste automatizado Cedro Technologies").append("                </div>")
				.append("            </td>").append("        </tr>").append("    </table>")
				.append("    <!-- pre-header end -->").append("    <!-- header -->")
				.append("    <table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"ffffff\">")
				.append("").append("        <tr>").append("            <td align=\"center\">")
				.append("                <table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\" cellspacing=\"0\" class=\"container590\">")
				.append("").append("                    <tr>")
				.append("                        <td height=\"25\" style=\"font-size: 25px; line-height: 25px;\"> </td>")
				.append("                    </tr>                   ").append("                    <tr>")
				.append("                        <td height=\"25\" style=\"font-size: 25px; line-height: 25px;\"> </td>")
				.append("                    </tr>").append("").append("                </table>")
				.append("            </td>").append("        </tr>").append("    </table>")
				.append("    <!-- end header -->").append("").append("    <!-- big image section -->")
				.append("    <table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"ffffff\" class=\"bg_color\">")
				.append("").append("        <tr>").append("            <td align=\"center\">")
				.append("                <table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\" cellspacing=\"0\" class=\"container590\">")
				.append("                    <tr>").append("")
				.append("                        <td align=\"center\" class=\"section-img\">")
				.append("                            <a href=\"\" style=\" border-style: none !important; display: block; border: 0 !important;\"><img src=\"https://liberdadedigitalhoje.com/wp-content/uploads/2016/08/offline.png\" style=\"display: block; width: 200px;\" width=\"200\" border=\"0\" alt=\"\" /></a>")
				.append("").append("").append("").append("").append("                        </td>")
				.append("                    </tr>").append("                    <tr>")
				.append("                        <td height=\"20\" style=\"font-size: 20px; line-height: 20px;\"> </td>")
				.append("                    </tr>").append("                    <tr>")
				.append("                        <td align=\"center\" style=\"color: #343434; font-size: 24px; font-family: Quicksand, Calibri, sans-serif; font-weight:700;letter-spacing: 3px; line-height: 35px;\" class=\"main-header\">")
				.append("").append("").append("                            <div style=\"line-height: 35px\">")
				.append("")
				.append("                                SISTEMA<span style=\"color: #FE0000;\"> OFFLINE</span>")
				.append("").append("                            </div>").append("                        </td>")
				.append("                    </tr>").append("").append("                    <tr>")
				.append("                        <td height=\"10\" style=\"font-size: 10px; line-height: 10px;\"> </td>")
				.append("                    </tr>").append("").append("                    <tr>")
				.append("                        <td align=\"center\">")
				.append("                            <table border=\"0\" width=\"40\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"eeeeee\">")
				.append("                                <tr>")
				.append("                                    <td height=\"2\" style=\"font-size: 2px; line-height: 2px;\"> </td>")
				.append("                                </tr>").append("                            </table>")
				.append("                        </td>").append("                    </tr>").append("")
				.append("                    <tr>")
				.append("                        <td height=\"20\" style=\"font-size: 20px; line-height: 20px;\"> </td>")
				.append("                    </tr>").append("").append("                    <tr>")
				.append("                        <td align=\"center\">")
				.append("                            <table border=\"0\" width=\"400\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"container590\">")
				.append("                                <tr>")
				.append("                                    <td align=\"center\" style=\"color: #888888; font-size: 16px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 24px;\">")
				.append("").append("")
				.append("                                        <div style=\"line-height: 24px\">").append("")
				.append("                                            Nosso robô tester identificou que o sistema ficou OFFLINE e enviou essa mensagem.")
				.append("                                        </div>")
				.append("                                    </td>").append("                                </tr>")
				.append("                            </table>").append("                        </td>")
				.append("                    </tr>").append("").append("                    <tr>")
				.append("                        <td height=\"25\" style=\"font-size: 25px; line-height: 25px;\"> </td>")
				.append("                    </tr>").append("                </table>").append("")
				.append("            </td>").append("        </tr>").append("").append("    </table>").append("	<br>")
				.append("    <!-- end section -->").append("    <!-- footer ====== -->")
				.append("    <table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"f4f4f4\">")
				.append("").append("        <tr>")
				.append("            <td height=\"25\" style=\"font-size: 25px; line-height: 25px;\"> </td>")
				.append("        </tr>").append("").append("        <tr>").append("            <td align=\"center\">")
				.append("")
				.append("                <table border=\"0\" align=\"center\" width=\"590\" cellpadding=\"0\" cellspacing=\"0\" class=\"container590\">")
				.append("").append("                    <tr>").append("                        <td>")
				.append("                            <table border=\"0\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\" class=\"container590\">")
				.append("                                <tr>")
				.append("                                    <td align=\"left\" style=\"color: #aaaaaa; font-size: 14px; font-family: 'Work Sans', Calibri, sans-serif; line-height: 24px;\">")
				.append("                                        <div style=\"line-height: 24px;\">").append("")
				.append("                                            <span style=\"color: #333333;\">Cedro Technologies</span>")
				.append("").append("                                        </div>")
				.append("                                    </td>").append("                                </tr>")
				.append("                            </table>").append("")
				.append("                            <table border=\"0\" align=\"left\" width=\"5\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\" class=\"container590\">")
				.append("                                <tr>")
				.append("                                    <td height=\"20\" width=\"5\" style=\"font-size: 20px; line-height: 20px;\"> </td>")
				.append("                                </tr>")
				.append("                            </table>                   ")
				.append("                        </td>").append("                    </tr>").append("")
				.append("                </table>").append("            </td>").append("        </tr>").append("")
				.append("        <tr>")
				.append("            <td height=\"25\" style=\"font-size: 25px; line-height: 25px;\"> </td>")
				.append("        </tr>").append("").append("    </table>").append("    <!-- end footer ====== -->")
				.append("").append("</body>").append("").append("</html>");

		return myvar.toString();

	}

}
